spring:
  redis:
    host: ${REDIS_HOST}
    port: 6379
    password: ${REDIS_PASSWORD}
    database: 0
  main:
    allow-bean-definition-overriding: true

dynamic:
  hot:
    cache:
      cachePoolPrefix: cachepool
      allKeyPoolPrefix: allkeypool
      fastSamplesNums: 5
      fastSamplesTime: 1000
      slowSamplesNums: 10
      slowSamplesTime: 3000
      hotCacheNums: 10
      strategy-type: lru
      regularlyUpdateCacheInterval: 500
      enable: true

task:
  pool:
    coreSize: 8
    maxSize: 16
    queueCapacity: 30