spring:
  redis:
    host: ${REDIS_HOST}
    port: 6379
    password: ${REDIS_PASSWORD}
    database: 0
  main:
    allow-bean-definition-overriding: true
  task:
    execution:
      pool:
        core-size: 4
        max-size: 8
        queue-capacity: 15

dynamic:
  hot:
    cache:
      cachePoolPrefix: cachepool
      allKeyPoolPrefix: allkeypool
      samplesNums: 5
      hotCacheNums: 10
      strategy-type: lru
      enable: true